### ISSUE TITLE
使用require的一个疑问

### ISSUE THREAD

**Issue by xcchcaptain** [aui/artDialog#107]
在弹出层中加载一个页面，未使用iframe
此时在加载的页面该如何使用require呢
@aui 
其实问题是
在使用require加载模块的情况下，该如何在弹出层中响应事件（比如提交事件），继续弹出弹出层
不知有没有类似使用的案例？

**Comment by km3945** [comment]
@xcchcaptain
在onshow事件中对DOM绑定事件.
