### ISSUE TITLE
V6使用url加载一个页面,OK按钮怎么去提交url页面里的表单呢?谢谢!

### ISSUE THREAD

**Issue by meihangbo** [aui/artDialog#119]
V6使用url加载一个页面,OK按钮怎么去提交url页面里的表单呢?谢谢!

**Comment by hiword** [comment]
@meihangbo 请问你是如何解决的，我也急需解决此问题

**Comment by meihangbo** [comment]
@hiword 作者已经给出方案了...
var iframeWindow = this.iframeNode.contentWindow;
iframeWindow.document.getElementById('form-id').submit();
iframeWindow 就是弹出框的iframe,也就是url页面的iframe.
得到了这个,那操作url页面里dom就简单樂.  

iframeWindow.document.getElementById('form-id')   拿到的就是表单.想怎么操作都成..
