### ISSUE TITLE
设置cancelValue,但不设置cancel,没有取消按钮

### ISSUE THREAD

**Issue by blqw** [aui/artDialog#180]
dialog({cancelValue:"取消",title:"xxx"}).show()
![qq 20150106172011](https://cloud.githubusercontent.com/assets/9656154/5626581/49363a7a-95c8-11e4-96f1-999c3bf916bc.png)

**Comment by aui** [comment]
要有事件才会有按钮，`cancelValue`只是描述按钮的文本。解决方案：`cancel:function(){}`
