### ISSUE TITLE
如何 修改 对话框的初始 显示位置

### ISSUE THREAD

**Issue by yangbo7907** [aui/artDialog#183]
你好，
请教一个问题， 我现在用的5.0.4的版本， 我现在想将弹出的对话框的 初始位置 放在浏览器的底部，请问我该如何做呢， 看文档并没有发现相关参数，谢谢了。

**Comment by aui** [comment]
已经不支持此功能了

**Comment by yangbo7907** [comment]
谢谢您的快速回答，请问有什么变通方法么， 例如直接修改哪个 css 文件？ 需要这个功能
