### ISSUE TITLE
当内容有比较多的时候能不能自动出现滚动条

### ISSUE THREAD

**Issue by jroam** [aui/artDialog#188]
当内容有比较多的时候能不能自动出现滚动条?
现在是不出现，结果出现，内容显示要弹出框以外的地方去了。

**Comment by udbmnm** [comment]
会出现滚动条，但是滚动不了，不知道滚动事件是不是被阻止了

**Comment by lhyaax** [comment]
嗯嗯，希望能自动出现滚动条。还有窗口右上角搞个最大化就好了。

**Comment by aui** [comment]
业务 css：给容容器设置尺寸，并且设置`overflow:auto`
