### ISSUE TITLE
iframe .close().show()之后再关闭会带上次服务端返回值触发close监听事件

### ISSUE THREAD

**Issue by oppoic** [aui/artDialog#197]
作者辛苦了，描述下我使用artDialog遇到的问题，希望百忙中抽空看看：
页面1：设置页面（类似模板页），页面里有如下js：
![Image of Yaktocat](http://images.cnitblog.com/blog/401362/201501/261416512534708.jpg)

监听弹框的close事件，同时拿到服务端具体的错误/成功信息用noty提示框提示给用户。

页面2：artDialog iframe内嵌页面，用户点击页面1里的某个按钮，artDialog iframe弹框设置，弹框内容就是页面2，页面2里面有这样一段js：
![Image of Yaktocat](http://images.cnitblog.com/blog/401362/201501/261417081759377.jpg)

用户设置之后提交，服务端返回msg.Success是True的话，那么销毁对话框，同时close事件把服务端具体的消息传到页面1，页面1里的messagetip()函数会提示用户成功了。
如果msg.Success是False的话，同样通过close事件把服务端的具体错误信息传给messagetip()函数，然后提示用户什么原因导致失败，但是跟操作成功有区别的是，这里不能销毁对话框了，用户设置失败，提示的同时对话框得保留着（逻辑上是这样的），因为只有close事件可以带参数回去，所以就先close一下，不销毁的情况下再showModel出来，到这都没问题，但是如果这个时候如果点右上角叉叉直接关闭对话框，也会触发close事件，触发倒没事，但是上一回错误信息也带回去了，这是为何？
总结：用户提交，服务端返回：{"Success":false,"Message":"测试出错！"}，用户不提交了，直接点右上角的叉叉关闭，监听close事件的函数还是能收到：{"Success":false,"Message":"测试出错！"}，是我使用问题么？有什么好的方式可以解决我的使用场景？不关闭对话框也可以把参数带回去。

**Comment by aui** [comment]
能否将问题简化下？

**Comment by oppoic** [comment]
简化：
一个artDialog弹框呈现一个表单，用户点击提交服务端返回的值有两种情况：
1：{"Success":true,"Message":"测试成功！"}
2：{"Success":false,"Message":"测试出错！"}

第一种情况表示提交成功，直接销毁对话框即可，
第二种情况，逻辑上应该不关闭弹框（但是我为了带值回去，还是调用了close(result)方法，然后立即showModel()），提示错误，用户可以继续修改表单数据进行提交。但是一旦服务端返回第二种情况，用户不修改数据直接点击右上角的叉关闭弹框也会触发close事件，同时带了上一回服务端的返回值触发的close事件，理应不应该这样吧？

代码都在上面，作者是否看下，还是我使用问题？

**Comment by oppoic** [comment]
dialog.close(msg);前面手动设置：this.returnValue="";解决了
