### ISSUE TITLE
用top.dialog时会有跨域的问题，请教如何解决

### ISSUE THREAD

**Issue by liangei** [aui/artDialog#200]
有三个页面
主页面 home.baidu.com用iframe套着sub.baidu.com
sub.baidu.com里有个一查看的按钮 点击它就弹出sub.baidu.com/dialog.php

在sub.baidu.com下点击 查看就没有问题 
但在home.baidu.com下点击就出现了跨域的问题。请教一下如何解决？

**Comment by aui** [comment]
请 google `js 跨域`，这个问题属于基础技术问题
