### ISSUE TITLE
oniframeload 回调函数中 想访问当前iframe

### ISSUE THREAD

**Issue by yiqing-95** [aui/artDialog#211]
如题，想在回调方法中用this 访问当前iframe对象 ，但查看代码发现并没有暴露类似这样的功能。
此需求源于，有时候iframe中内容太多了 滚条也没有显示，内容区底部被隐藏 也无法看到 所以想通过this来动态重置scrolling="yes" 属性 让滚动条显示出来

这个功能算是增强，对代码改动不会太大 希望糖饼 予以考虑

**Comment by aui** [comment]
滚动条可以通过设置内容页面的 overflow:auto 来解决啊。

如果访问 iframe 对象，可以使用 ``this.iframeNode``
