### ISSUE TITLE
在title里添加html标签，显示出html代码了。。

### ISSUE THREAD

**Issue by wslx520** [aui/artDialog#219]
比如 title:'<b>1</b> 管理岗位分配',，这样就会把代码也显示出来，并没有把b当成html标签处理。

我是跨iframe调用的。

如果要在title里加标签，该怎么做呢？

**Comment by aui** [comment]
title区域不支持html

**Comment by wslx520** [comment]
为什么加入这个限制呢？我觉得不加应该更不费代码吧？
