### ISSUE TITLE
v4中多个弹窗问题

### ISSUE THREAD

**Issue by yipanbo** [aui/artDialog#223]
我们项目使用了大神的artDialog，version：4.1.2，主要使用的是iframe，引用多个页面，但是遇到了点问题。
比如我弹出一个dialog，其中有个添加按钮，点击添加按钮之后又弹出一个dialog，此时我把第一个dialog关闭的时候，第二个dialog也被关闭。
我们想要的效果是：关闭第一个dialog时，第二个dialog不被关闭，这个怎么处理？
谢谢！

**Comment by aui** [comment]
dialog 设计：调用对话框的函数所在的 widnow 必须存在，如果 window 被注销则会自动关闭对话框。

解决方案：在父页面声明对话框

**Comment by yipanbo** [comment]
见到大神了，先激动一会

**Comment by yipanbo** [comment]
这个办法可以，但是如果在父页面声明的话，我的第二个dialog关闭时，还想刷新第一个dialog页面，这个好像就麻烦了
