### ISSUE TITLE
您是如何统计有哪些项目用了你的插件的

### ISSUE THREAD

**Issue by giantray** [aui/artDialog#227]
请教下，您是如何统计有哪些项目用了你的插件的？我正在做相关的工作，挺犯愁的。

**Comment by aui** [comment]
来自：网友反馈

**Comment by giantray** [comment]
"四年来，有超过 40 万网站在使用 artDialog，其中不乏国内顶尖的产品"
这40万都是网友人肉反馈？

**Comment by aui** [comment]
40W 是来自最大的用户 —— 盛大旗下 PHPCMS 产品团队反馈

**Comment by giantray** [comment]
了解，佩服佩服

**Comment by Jason-mor** [comment]
@giantray 请问你的统计工具最后是根据什么原理做的？

**Comment by giantray** [comment]
@Jason-mor ,最后还是没有很合理的解决方式
