### ISSUE TITLE
我可以自定义一个关闭按钮吗？

### ISSUE THREAD

**Issue by blwoosky** [aui/artDialog#251]
我可以指定一个弹框内的任意一个内容做为关闭按钮吗？

**Comment by xdqa01** [comment]
//当内容是一个Html元素时
jQuery("xxx").click(function(){ dialog.getTop().close();});
//如果是文字内容作为关闭按钮，需要在onshow时将文字使用span\div包裹，并注册click事件
dialog({title:"标题",content:"我要关闭",onshow:function(){
var $b= this.__Popup.find(".ui-dialog-body");
var h=$b.html();
h=h.replace("关闭","<span onclick='dialog.getTop().close()'>关闭</span>");
$b.html(h);
}});
以上适用于artDialog v6 dialogPlus版本

**Comment by xdqa01** [comment]
dialog.getTop = function () {
        /// <summary>
        /// 获取顶层对话框
        /// dialog.getCurrent()只能获取最近一次的对话框
        /// 当先开启的对话框未关闭，后开启的对话框已关闭时始终返回null
        ///</summary>
        var _Cur = null;
        for (var key in dialog.list) {
            var dlg = dialog.list[key];
            if (dlg.open) {
                if (_Cur == null || key > _Cur.id)
                    _Cur = dlg;
            };
        };
        return _Cur;
    };

**Comment by xdqa01** [comment]
作者给的参考文档基本上够用了。
http://js/scripts/artDialog6.04/artDialog-master/doc/
