### ISSUE TITLE
大神进来。求解

### ISSUE THREAD

**Issue by canvey** [aui/artDialog#271]
现在的项目其中一个功能是ajax的登录窗口。
当用户登录超时或者没有登录，会弹出提示用户的dialog。弹出这个dialog，需要把关闭其它dialog再显示出来（顺序无妨，先显示再关闭都可以）。如何操作？
其次，待登录成功后，关闭登录dialog，显示上一次关闭的dialog

求大神指教！！！

**Comment by lcoder** [comment]
业务逻辑的层次，你弹窗来的dialog push进一个数组，登录成功之类，遍历数组，一次show出之前关闭的dialog不就好了？
