### ISSUE TITLE
如何让整个dialog插入在指定div中，不默认插入body里面

### ISSUE THREAD

**Issue by chengdongwei** [aui/artDialog#282]
![image](https://cloud.githubusercontent.com/assets/10320249/17510020/84da117c-5e4f-11e6-80bb-de4566b683d4.png)
![image](https://cloud.githubusercontent.com/assets/10320249/17510025/947751b2-5e4f-11e6-8b74-b4634cba29aa.png)

**Comment by aui** [comment]
这里似乎超出了边界了，暂时无法支持
