### ISSUE TITLE
最新版本还兼容IE7，IE8吗？

### ISSUE THREAD

**Issue by OuFeng** [aui/artDialog#298]
糖饼前辈您好，我最近基于公司的业务需要一套兼容IE7，IE8的弹窗库; 查了很多主流的弹窗库，发觉还是artDialog很符合公司的业务。 不过当我下载下来在IE7，IE8上面试着运行的时候发现代码run不起来，所以想请问一下是什么原因呢。。。？ 是不是我使用不当呢？

**Comment by lcoder** [comment]
不要用最新的，不要用最新的，artDialog4.1.7 就能符合你的要求。我感觉这个版本没有之前的好用，很多功能有点鸡肋

**Comment by beanLau** [comment]
在哪下载4.1.7呢？

**Comment by lcoder** [comment]
百度第一个就有
