### ISSUE TITLE
artdialog 在开源项目中使用，是否收费

### ISSUE THREAD

**Issue by SundyTyy** [aui/artDialog#303]
artdialog 在开源项目中使用，是否收费

**Comment by aui** [comment]
<https://github.com/aui/artDialog/blob/master/LICENSE.md>

**Comment by SundyTyy** [comment]
这个是在开发中版本的LICENSE，这个版本可以直接使用吗？可以提供有版本号的版本吗？

**Comment by aui** [comment]
art-dialog 历史版本有不同的 LICENSE。如果对特定版本的 LICENSE 有疑问，你可以去查看包中的 LICENSE 文件。

**Comment by SundyTyy** [comment]
现在master分支的可以用吗？https://github.com/aui/artDialog/blob/master/LICENSE.md这个license固定吗？

**Comment by aui** [comment]
art-dialog 是使用标准的开源协议、标准的声明方式声明的授权，如果对此有问题我建议你先去了解下这方面的知识，否则我怎么解释都是多余的。

**Comment by SundyTyy** [comment]
我清楚LGPL开源协议是什么意思，但6.0.2版本，在license里边明确提到了软件商用收费。在readme文件里边写的是免费，且开源，基于LGPL协议。

**Comment by SundyTyy** [comment]
这个的意思是我们遵守LGPL协议规范，使用了且开源出来就是免费的吗？商用就收费？麻烦明确下我对这两个文件的内容理解是否正确？

**Comment by SundyTyy** [comment]
另外7.0.0 版本的license里边没有提到商业授权费用问题，是不是意味着这个版本是完全免费的？
