### ISSUE TITLE
在chrome下 form 不能提交

### ISSUE THREAD

**Issue by zhangzhongfei** [aui/artDialog#308]
报错： Form submission canceled because the form is not connected
网上说 是因为chrome 修复了bug 导致的 需要将form追加大dom中，我看代码 插件已经追加到dom中了

代码如下：
     var d = dialog({
            	quickClose:true,
                content:'<form action="。。。。" method="post" id="switch">' +
                '<div class="form-group">' +
                '<label class="control-label">切换用户组</label>' +
                '<select class="form-control" name="groupid">' +
                '<option value="1">超级管理员</option>' +
                '<option value="2">普通管理员</option>' +
                '<option value="3">编辑</option>' +
                '<option value="4">频道</option>' +
                '</select>' +
                '</div>' +
                '<div class="form-group">' +
                '<input type="hidden" value="" name="username" id="uname">' +
                '<input type="submit" value="提交" class="btn btn-primary " >' +
                '</div>' +
                '</form>'
            });
            d.showModal();

**Comment by aui** [comment]
不明白你的问题

**Comment by zhangzhongfei** [comment]
在chorme浏览器下没法提交form表单  报错 Form submission canceled because the form is not connected

**Comment by aui** [comment]
没明白和 dialog 有啥关系，他不过是一个浮层

**Comment by zhangzhongfei** [comment]
我浮层的内容就是一个form表单呀 我贴出了源码，想问问有没有人遇到这中情况

**Comment by aui** [comment]
提交 BUG 之前请先自己排查，如果要别人排查问题：

1. 先把 demo 代码格式好
2. 列出 chrome 版本号与 art-dialog 版本号

如果不能达到上述要求，问题会保持关闭状态
