### ISSUE TITLE
这个插件自带keydown事件? 

### ISSUE THREAD

**Issue by lyingfromyou** [aui/artDialog#317]
在弹出窗口中的input框中直接按enter键, 会自动提交表单, 这是为什么?  有什么办法去除吗

**Comment by aui** [comment]
你遇到问题之前，能否搜索一下源代码 `keydown` 关键字、然后再提你解决不了的问题？

**Comment by Smoke-N-Mirrors** [comment]
> 你遇到问题之前，能否搜索一下源代码 `keydown` 关键字、然后再提你解决不了的问题？

牛逼哄哄的,吹牛逼
