### ISSUE TITLE
弹框有bug

### ISSUE THREAD

**Issue by shimanshe** [aui/artDialog#338]
刚开始觉得挺好，但是后面发现bug，如果页面很长的时候，老是对话框显示会调到，页面也跟着滚动到底部，这个没法接受了。设置了fixed，居然不能设置top，然而你们的top计算又有问题。

**Comment by shimanshe** [comment]
用这个解决了。
var mask = dialog({
			title: '字体',
			content: $(".font-panel").html(),
			cancel: true,
			fixed: true,
			cancelDisplay: false,
			onshow: function () {
				$(".ui-popup-modal").css({top:"100px"});
			}
		});
		mask.width(200).showModal();

**Comment by aui** [comment]
我觉得你需要整理下文字后再提 BUG 比较好，因为根本不知道你那边是什么问题
