### ISSUE TITLE
v6问题集

### ISSUE THREAD

**Issue by xuexb** [aui/artDialog#67]
###  已知的实用方法没了
1. `time` 定时
2. 用 `onshow` 代替 `initialize` 有问题，如果有id存在第二次执行还会走 `onshow` 但以前的 `initialize` 却不执行
3. ie7-- button不会居中，会居右
4. sea给大部分人群造成困扰
5. 是否考虑扩展一个 `关闭开关` 的方法， 很多场景下会让某个弹出层不能关闭，操作某块后可关闭，以前版本可通过 `art.config.beforeunload = function(){return false;}`， 在可关闭时用 `art.config.beforeunload = null;` 但v6发现重构后同样思路不可用(可能能力有限)
6. v6的结构感觉没有v5好，v5分的很清，很容易明白，v6的架子有点不懂了

###  优点：
1. 提示层很实用
2. 支持模板扩展不错（+skin）

**Comment by MINSTONEFE** [comment]
有没有 left: '10%'，top: '10% 这样子的自定义定位功能？？？求 @aui 帮忙。

**Comment by aui** [comment]
@MINSTONEFE 不支持此

**Comment by MINSTONEFE** [comment]
@aui 恩，我自己改源码了。
